social:
  - name: 'Github'
    link: 'https://github.com/shotsuke'
  - name: 'Bilibili'
    link: 'https://space.bilibili.com/32768166'
  - name: 'Steam'
    link: 'http://steamcommunity.com/id/Shotsuke'

menu: # 页眉菜单项目
  home: /
  about: /about/
  categories: /categories/
  archives: /archives/
  friends: /friends/

mathjax:
  enable: true
  cdn: https://cdn.jsdelivr.net/npm/mathjax@2.7.8/MathJax.js?config=TeX-AMS-MML_HTMLorMML